### ISSUE TITLE
가상 hdd img를 사용한 os 실행은 안될까요?

### ISSUE THREAD

**Issue by dlarudgus20** [kbu1564/HelloOS#27]
USB 메모리를 이용해서 os를 개발하시는 듯 한데, 하드디스크 이미지 파일을 뱉게 하는 건 어떤가요? 쓸만한 usb도 없고 해서요 ㅎㅎ,,
한번 구경해보려고 받아서 make 했더니 `cp Image/kernel.sys /cygdrive/e/kernel.sys` 라면서 에러가 떠서 E: 도 없는데 도대체 뭐지.. 했네요 makefile뜯어본 다음에 알게된..

(c언클 암겨혀입니다)

**Comment by kbu1564** [comment]
음 이부분은 별도로 설치파일로 해서 제공하려는 생각은 있지만 이미지 파일 형식으로 제공되도록은
아직 생각하지 않고 있습니다.

추후 말하신 방법으로도 제공될 수 있도록 프로젝트를 새로 하나 개설하는 쪽으로 고려해 보겠습니다.
:)

**Comment by dlarudgus20** [comment]
음.. 프로젝트 하나 만들 정도인건가요..? makefile에서 명령행으로 만들 수 있지 않나요? osdev위키에 있던데.. (운영체제마다 달라서 좀 까다로운듯 하지만요)
쨋든 아쉽네요 ㅎ 실제 디바이스 사용하기가 뭐해서... 스크린샷 올려주시면 그거나 봐야겠어요 ㅋㅋ

**Comment by kbu1564** [comment]
@dlarudgus20 설치 가능한 usb의 목록을 체크하여 자동으로 mbr 영역과 그쪽으로 운영체제 관련 파일들을 복사 시키는 방식으로 윈도우와 리눅스 버전의 소스 프로그램을 제작할 생각이었던 터라

별도의 프로젝트로 만든다는 말 이었습니다 ^^

README.md 파일에 설치 방식을 추후 올리도록 하겠습니다.

---

**추가**
생각해보니 필요성은 충분히 있는것 같습니다.
말씀하신대로 지원할 경우 추후 운영체제의 버전과 관계없는 개발이 가능해 질 것이므로

말씀해 주신 이슈는 중요하게 다루어야 할것 같네요 :)
감사합니다.

해당 이슈는 다시 재 오픈 하겠습니다.

**Comment by dlarudgus20** [comment]
참고로 말하자면 제 clubcos같은 경우는 [edimg](http://hrb.osask.jp/wiki/?tools/edimg) 라는 "OS 30일 개발 프로젝트" 책에 딸려온 유틸을 소스를 <strike>복붙..아니</strike>손보고 해서 쓰고있어요. FAT12 플로피 이미지를 손봐주는 녀석인데.. 운영체제에 따라 방법을 달리하는게 더러운 거 같으면 이렇게 툴을 만들어버리는것도 나쁘지 않을거 같네요.

**Comment by kbu1564** [comment]
프로젝트 초기 목적에 의해 본 이슈를 닫습니다.
자세한 설치 방법은 README.md 를 참조 부탁드립니다.
